### ISSUE TITLE
Anyway to undo randify?

### ISSUE THREAD

**Issue by Robby-Sodhi** [tinyioda/Randify#4]
Randomized my playlist any way to undo it lol Do I have to contact spotify support?

**Comment by Laiteux** [comment]
Hey, same here. Wasn't expecting this to happen, I can't even sort my songs by "add date" anymore, kinda mad rn. Did you end up fixing your issue? How? Thank you. I strongly believe Randify should add a disclaimer...

**Comment by Robby-Sodhi** [comment]
> Hey, same here. Wasn't expecting this to happen, I can't even sort my songs by "add date" anymore, kinda mad rn. Did you end up fixing your issue? How? Thank you. I strongly believe Randify should add a disclaimer...

I contacted Spotify support and they don’t store orders of songs in backups as far as I can tell so they weren’t able to revert the order back. I’d try maybe you’ll have better luck than I had however I think just gonna have to live with it
